config/routes.rb
NetworkBuilder::Application.routes.draw do
  resources :locations

  get 'home/index'
  resources :networks do
    resources :points
  end
  
  root to: 'home#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/network.rb
class Network < ActiveRecord::Base
  has_many :points, dependent: :destroy
  accepts_nested_attributes_for :points
end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :network
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @network_links = NetworkLink.all
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :description, :icon, :lat, :lng)
    end
end

app/controllers/networks_controller.rb
class NetworksController < ApplicationController
  before_action :set_network, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  # GET /networks
  def index
    @networks = Network.includes(:points)
  end

  # GET /networks/1
  def show
  end

  # GET /networks/new
  def new
    @network = Network.new
    2.times{ @network.points.build }
  end

  # GET /networks/1/edit
  def edit
    2.times{ @network.points.build }
  end

  # POST /networks
  def create
    @network = Network.new(network_params)

    respond_to do |format|
      if @network.save
        format.html { redirect_to @network, notice: 'Network was successfully created.' }
        format.json { render action: 'show', status: :created, network: @network }
      else
        format.html { render action: 'new' }
        format.json { render json: @network.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /networks/1
  def update
    respond_to do |format|
      if @network.update(network_params)
        format.html { redirect_to @network, notice: 'Network was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @network.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /networks/1
  def destroy
    @network.destroy
    respond_to do |format|
      format.html { redirect_to networks_url, notice: 'Network was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_network
      @network = Network.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def network_params
      params.require(:network).permit(:name, :color, :capacity, :description, points_attributes: [:lat, :lng])
    end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_network
  before_action :set_point, only: [:show, :edit, :update, :destroy]

  # GET /points
  def index
    @points = Point.all
  end

  # GET /points/1
  def show
  end

  # GET /points/new
  def new
    @point = Point.new
  end

  # GET /points/1/edit
  def edit
  end

  # POST /points
  def create
    @point = Point.new(point_params)

    if @point.save
      redirect_to [@network, @point], notice: 'Point was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /points/1
  def update
    if @point.update(point_params)
      redirect_to [@network, @point], notice: 'Point was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /points/1
  def destroy
    @point.destroy
    redirect_to network_points_url(@network), notice: 'Point was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_network
      @network = Network.find(params[:network_id])
    end

    def set_point
      @point = Point.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def point_params
      params.require(:point).permit(:network_id, :lat, :lng)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ALERT_TYPES = [:error, :info, :success, :warning]

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = :success if type == :notice
      type = :error   if type == :alert
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if message
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/home/_form.html.haml
= form_for NetworkLink.new(capacity: 5, color: '#55FF00'), remote: true do |f|
  = f.hidden_field :start_lat
  = f.hidden_field :start_lng
  = f.hidden_field :end_lat
  = f.hidden_field :end_lng
  .field
    = f.label :capacity
    = f.number_field :capacity
  .field
    = f.label :color
    = f.text_field :color
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/home/index.html.haml
#map

- content_for :sidebar do
  %h4 Networks
  %a.btn#add_network_btn= 'Add network'
  #add_network{style: 'display: none'}
    = text_field_tag :network_name, '', {placeholder: 'name'}
    = text_area_tag :network_description, '', {placeholder: 'description'}
    = number_field_tag :network_capacity, ''
    = text_field_tag :network_color, '', {type: 'color'}
    %a.btn#save_network= 'Save'
  %h4 Locations
  %a.btn#add_location_btn= 'Add location'
  #add_location{style: 'display: none'}
    = text_field_tag :location_name, '', {placeholder: 'name'}
    = text_area_tag :location_description, '', {placeholder: 'description'}
    = hidden_field_tag :location_icon, '', {placeholder: 'icon'}
    %a.btn#save_location= 'Save'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "NetworkBuilder"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")

  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") NetworkBuilder
          .container.nav-collapse
            %ul.nav
              %li= link_to "Map", root_path
              %li= link_to "Networks", networks_path
              %li= link_to "Locations", locations_path

    .container-fluid
      .row-fluid
        - if content_for? :sidebar
          .span3
            .well.sidebar-nav= yield(:sidebar)
          .span9
            = bootstrap_flash
            = yield
        - else
          .span12
            = bootstrap_flash
            = yield

      %footer
        %p &copy; 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyB28N7hKAQBbSQxqZLVPFs3HygkHBo3o1Y&sensor=false"
    = yield(:javascript)

app/views/locations/_form.html.haml
= form_for @location do |f|
  - if @location.errors.any?
    #error_explanation
      %h2= "#{pluralize(@location.errors.count, "error")} prohibited this location from being saved:"
      %ul
        - @location.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :icon
    = f.text_field :icon
  .field
    = f.label :lat
    = f.text_field :lat
  .field
    = f.label :lng
    = f.text_field :lng
  .actions
    = f.submit 'Save'

app/views/locations/edit.html.haml
%h1 Editing location

= render 'form'

= link_to 'Show', @location
\|
= link_to 'Back', locations_path

app/views/locations/index.html.haml
%h1 Listing locations

%table.table.table-stripped
  %tr
    %th Name
    %th Description
    %th Icon
    %th Lat
    %th Lng
    %th
    %th
    %th

  - @locations.each do |location|
    %tr
      %td= location.name
      %td= location.description
      %td= location.icon
      %td= location.lat
      %td= location.lng
      %td= link_to 'Show', location, class: 'btn'
      %td= link_to 'Edit', edit_location_path(location), class: 'btn'
      %td= link_to 'Destroy', location, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn'

%br

= link_to 'New Location', new_location_path

app/views/locations/new.html.haml
%h1 New location

= render 'form'

= link_to 'Back', locations_path

app/views/locations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @location.name
%p
  %b Description:
  = @location.description
%p
  %b Icon:
  = @location.icon
%p
  %b Lat:
  = @location.lat
%p
  %b Lng:
  = @location.lng

= link_to 'Edit', edit_location_path(@location)
\|
= link_to 'Back', locations_path

app/views/networks/_form.html.haml
= form_for @network do |f|
  - if @network.errors.any?
    #error_explanation
      %h2= "#{pluralize(@network.errors.count, "error")} prohibited this network from being saved:"
      %ul
        - @network.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :color
    = f.text_field :color
  .field
    = f.label :capacity
    = f.number_field :capacity
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.fields_for :points do |p|
      = p.text_field :lat
      = p.text_field :lng
  .actions
    = f.submit 'Save'

app/views/networks/edit.html.haml
%h1 Editing network

= render 'form'

= link_to 'Show', @network
\|
= link_to 'Back', networks_path

app/views/networks/index.html.haml
%h1 Listing networks

%table.table.table-striped
  %tr
    %th Name
    %th Color
    %th Capacity
    %th Description
    %th Number of points
    %th
    %th
    %th

  - @networks.each do |network|
    %tr
      %td= network.name
      %td= network.color
      %td= network.capacity
      %td= network.description
      %td= network.points.count
      %td= link_to 'Show', network, class: 'btn'
      %td= link_to 'Edit', edit_network_path(network), class: 'btn'
      %td= link_to 'Destroy', network, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn'

%br

= link_to 'New Network', new_network_path

app/views/networks/new.html.haml
%h1 New network

= render 'form'

= link_to 'Back', networks_path

app/views/networks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @network.name
%p
  %b Color:
  = @network.color
%p
  %b Capacity:
  = @network.capacity
%p
  %b Description:
  = @network.description

= link_to 'Edit', edit_network_path(@network)
\|
= link_to 'Back', networks_path

app/views/points/_form.html.haml
= form_for [@network, @point] do |f|
  - if @point.errors.any?
    #error_explanation
      %h2= "#{pluralize(@point.errors.count, "error")} prohibited this point from being saved:"
      %ul
        - @point.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :network
    = f.text_field :network
  .field
    = f.label :lat
    = f.text_field :lat
  .field
    = f.label :lng
    = f.text_field :lng
  .actions
    = f.submit 'Save'

app/views/points/edit.html.haml
%h1 Editing point

= render 'form'

= link_to 'Show', [@network, @point]
\|
= link_to 'Back', network_points_path(@network)

app/views/points/index.html.haml
%h1 Listing points

%table
  %tr
    %th Network
    %th Lat
    %th Lng
    %th
    %th
    %th

  - @points.each do |point|
    %tr
      %td= point.network
      %td= point.lat
      %td= point.lng
      %td= link_to 'Show', [@network, point]
      %td= link_to 'Edit', edit_network_point_path(@network, point)
      %td= link_to 'Destroy', [@network, point], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Point', new_network_point_path(@network)

app/views/points/new.html.haml
%h1 New point

= render 'form'

= link_to 'Back', network_points_path(@network)

app/views/points/show.html.haml
%p#notice= notice

%p
  %b Network:
  = @point.network
%p
  %b Lat:
  = @point.lat
%p
  %b Lng:
  = @point.lng

= link_to 'Edit', edit_network_point_path(@network, @point)
\|
= link_to 'Back', network_points_path(@network)